--- Logging error ---
Traceback (most recent call last):
  File "c:\python\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 94, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\auto_checklog.py", line 21, in pytest_runtest_setup
    test_steps.log_new_func(item.name, str(item.fspath) )
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 109, in log_new_func
    __step_info.new_func(name, path)
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 87, in new_func
    self.__log_case()
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 90, in __log_case
    self.step_logger.info("------------------------------------------------------")
Message: '------------------------------------------------------'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\python\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 94, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\auto_checklog.py", line 21, in pytest_runtest_setup
    test_steps.log_new_func(item.name, str(item.fspath) )
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 109, in log_new_func
    __step_info.new_func(name, path)
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 87, in new_func
    self.__log_case()
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 91, in __log_case
    self.step_logger.info("Func %s in file: %s" % (self.case_name, self.file_name))
Message: 'Func test_redis in file: C:\\liqi\\autoApiTestLiqi\\testcases\\Test_case2_pushMiniPro.py'
Arguments: ()
2020-06-23 18:07:42,610 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 121 - Test_case2_pushMiniPro - INFO - 老师微信是:wxid_ss245739845
2020-06-23 18:07:42,611 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 122 - Test_case2_pushMiniPro - INFO - key值是:wxid_ss245739845_PUSH_MINI_PRO_LIST
2020-06-23 18:07:42,740 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 125 - Test_case2_pushMiniPro - INFO - 最新放入redis的推小程序指令是:{'account': 'dongfangyao', 'accountWechatId': 'wxid_ss245739845', 'studentWechatId': 'lq1592904705109988', 'nsNickName': 'lq1592904705109988', 'studentRealWechatId': 'wxid_1592904705109988', 'serverTime': 1592906862894, 'retryCount': 1, 'operationType': 36, 'recordId': '1592906862398716', 'expireTime': 1593079662896, 'system': 'WE', 'additionalInfo': '高意向学员', 'notNeedCover': True, 'messageList': [], 'guideSpeech': '同学你好', 'programId': 'ws123', 'pictureTitle': '小程序', 'pictureImg': 'string', 'programURL': 'http:hh123.com?additionalProp1=&additionalProp2=&additionalProp3=', 'miniproType': 0, 'memoPicUrlsStr': '', 'personListIdStr': '', 'crowdListIdStr': '', 'labelListStr': ''}
2020-06-23 18:07:42,741 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 127 - Test_case2_pushMiniPro - INFO - redis中最新一条指令的recordId是：1592906862398716
2020-06-23 18:07:42,741 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 128 - Test_case2_pushMiniPro - INFO - 生成的recordId是：1592906862398716
2020-06-23 18:07:42,741 - process: 129768 - Test_case2_pushMiniPro.py - 日志 - 129 - Test_case2_pushMiniPro - INFO - redis中存在刚放入的推小程序指令
